### ISSUE TITLE
403 - The request could not be satisfied

### ISSUE THREAD

**Issue by ablankenship10** [Droplr/serverless-api-cloudfront#15]
After setting up my working API with this plugin, and pointing my domain in Route 53 to the distribution I can only get "403 The request could not be satisfied" errors. This is my config:

```
custom:
  apiCloudFront:
    certificate: arn:aws:acm:us-east-1:XXXXXXXXXXX:certificate/XXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXX
    domain: api.domain.com
    compress: true
    headers: all
    querystring: all
```

I tried using the url both as api.domain.com/stage/endpoint and api.domain.com/endpoint to no avail. (I want the former version so I can have both of my stages on the same api.domain.com address.)

What am I missing?
