### ISSUE TITLE
Not able to deploy service with multiple domains with cloudfront

### ISSUE THREAD

**Issue by huv1k** [Droplr/serverless-api-cloudfront#6]
Hey, i was not able to deploy service with multiple domains in cloudfront. My config is like:
```yml
custom:
  apiCloudFront:
    domain: 
      - abcd.com
      - efgh.com
    certificate: arn:aws:acm:us-east-1:000000000000:certificate/00000000-1111-2222-3333-444444444444
```
`An error occurred: ApiDistribution - Property validation failure: [Value of property {/DistributionConfig/Aliases/0} does not match type {String}].`
Any idea? What could be wrong?
